# Generated by Django 5.2.18 on 2026-10-07 10:28

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('gross_cents', models.PositiveBigIntegerField()),
                ('discount_cents', models.PositiveBigIntegerField(default=0)),
                ('net_cents', models.PositiveBigIntegerField()),
                ('coupon_code', models.CharField(blank=True, max_length=64)),
                ('coupon_percentage', models.PositiveSmallIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price_cents', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('orders_count__gte', 0)), name='customer_orders_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CHECKOUT_STARTED', 'Checkout Started')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=40)),
                ('scope', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=40)),
                ('resource_id', models.UUIDField()),
                ('response_status', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operation', 'scope', 'key'), name='unique_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='reservation', serialize=False, to='store.order')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed'), ('RELEASED', 'Released')], default='ACTIVE', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('release_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='store.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.customer'),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outcome', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='UNKNOWN', max_length=12)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_deadline', models.DateTimeField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('local_fault', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempt', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_cents', models.PositiveBigIntegerField()),
                ('line_total_cents', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='RewardProgram',
            fields=[
                ('key', models.CharField(default='default', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('orders_per_coupon', models.PositiveIntegerField(default=5)),
                ('percentage', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('orders_per_coupon__gte', 1)), name='reward_n_positive'), models.CheckConstraint(condition=models.Q(('percentage__gte', 1), ('percentage__lte', 100)), name='reward_x_valid')],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('percentage', models.PositiveSmallIntegerField()),
                ('milestone', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('REDEEMED', 'Redeemed')], default='AVAILABLE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_coupons', to='store.order')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='store.rewardprogram')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('customer',), name='one_open_cart_per_customer'),
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='store.reservation'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('gross_cents__gte', 0)), name='order_gross_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_cents__gte', 0)), name='order_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('net_cents__gte', 0)), name='order_net_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('gross_cents', django.db.models.expressions.CombinedExpression(models.F('discount_cents'), '+', models.F('net_cents')))), name='order_totals_balance'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('program', 'milestone'), name='unique_program_milestone'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 1), ('percentage__lte', 100)), name='coupon_percentage_valid'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_order__isnull', True), ('status', 'AVAILABLE')), models.Q(('owner_order__isnull', False), ('status', 'RESERVED')), models.Q(('owner_order__isnull', False), ('status', 'REDEEMED')), _connector='OR'), name='coupon_status_owner_valid'),
        ),
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['product', 'status', 'id'], name='inventory_alloc_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reservation__isnull', True), ('status', 'AVAILABLE')), models.Q(('reservation__isnull', False), ('status', 'RESERVED')), models.Q(('reservation__isnull', False), ('status', 'SOLD')), _connector='OR'), name='inventory_status_owner_valid'),
        ),
    ]
