# Generated by Django 5.2.18 on 2026-10-07 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakePayment',
            fields=[
                ('attempt_id', models.UUIDField(primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('outcome', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=12)),
                ('provider_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lose_response_once', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
